### ISSUE TITLE
-t option not working with zsh as default $SHELL

### ISSUE THREAD

**Issue by JavMatz** [orhun/kermit#22]
With **/usr/bin/zsh** or **/bin/zsh** as the default $SHELL:

Alacritty, kitty and st work as expected with their respective -t options but kermit does not. However, if I do

`kermit -e $(which bash) -t Foo`

then the -t option works.

If I change SHELL to **/bin/bash**, then the -t option for kermit works, but if I do

`kermit -e $(which zsh) -t Foo`

the option stops working again.

With the fish shell the option also works as expected.

**Comment by orhun** [comment]
Thanks for reporting! 🐻 

I realized when you use `zsh`, `window-title-changed` signal is never sent to the terminal for some reason. So I decided to set the terminal title early in the setup function instead of waiting for the callback.

48ae48c4ddf4d5ddc618ac78bd67c3d03e622222 should fix this issue.
